CREATE TABLE AGENDAMENTOS(
    ID_AGENDAMENTO INT PRIMARY KEY AUTO_INCREMENT,
    TIPO ENUM('CONSULTA', 'EXAME LABORATORIAL', 'EXAME DE IMAGEM', 'VACINA') NOT NULL,
    ID_PACIENTE INT NOT NULL,
    ID_PROFISSIONAL INT NOT NULL,
    DATA_HORA DATETIME NOT NULL,
    OBSERVACOES TEXT,
    FOREIGN KEY(ID_PACIENTE) REFERENCES PACIENTES(ID_PACIENTE),
    FOREIGN KEY(ID_PROFISSIONAL) REFERENCES FUNCIONARIOS(ID_FUNCIONARIO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;