CREATE TABLE AGENDAMENTOS(
    ID_AGENDAMENTO INT PRIMARY KEY AUTO_INCREMENT,
    TIPO ENUM('CONSULTA', 'EXAME LABORATORIAL', 'EXAME DE IMAGEM', 'VACINA') NOT NULL,
    ID_PACIENTE INT NOT NULL,
    ID_PROFISSIONAL INT NOT NULL,
    DATA_HORA DATETIME NOT NULL,
    OBSERVACOES TEXT,
    FOREIGN KEY(ID_PACIENTE) REFERENCES PACIENTES(ID_PACIENTE),
    FOREIGN KEY(ID_PROFISSIONAL) REFERENCES FUNCIONARIOS(ID_FUNCIONARIO)
<<<<<<< HEAD
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
=======
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
>>>>>>> 889f4aa8d837551ed7c7e14707d3e034159db329
