CREATE TABLE AGENDAMENTOS(
    ID_AGENDAMENTO INT PRIMARY KEY AUTO_INCREMENT,
    TIPO ENUM('CONSULTA', 'EXAME LABORATORIAL', 'EXAME DE IMAGEM', 'VACINA') NOT NULL,
    ID_PACIENTE VARCHAR(100) NOT NULL,
    ID_PROFISSIONAL VARCHAR(100) NOT NULL,
    DATA_HORA DATETIME NOT NULL,
    OBSERVACOES TEXT,
    FOREIGN KEY(NOME_PACIENTE) REFERENCES PACIENTES(ID_PACIENTE)
    FOREIGN KEY(NOME_PROFISSIONAL) REFERENCES FUNCIONARIOS(ID_FUNCIONARIO)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;