CREATE TABLE FUNCIONARIOS(
    ID_FUNCIONARIO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(16) UNIQUE NOT NULL,
    DATA_NASC DATE,
    SEXO ENUM('M', 'F') NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    

);