CREATE TABLE FUNCIONARIOS(
    ID_FUNCIONARIO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(16) UNIQUE NOT NULL,
    DATA_NASC DATE,
    SEXO ENUM('M', 'F') NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    FUNCAO ENUM('RECEPCIONISTA', 'MEDICO', 'ADMIN')
);

CREATE TABLE ENDERECO_FUNCIONARIOS(
    ID_ENDERECO INT PRIMARY KEY AUTO_INCREMENT,
    BAIRRO VARCHAR(60) NOT NULL,
	RUA VARCHAR(60) NOT NULL,
	NUMERO INT NOT NULL,
	CIDADE VARCHAR(40) NOT NULL,
	UF CHAR(2) NOT NULL,
    ID_FUNCIONARIO INT UNIQUE,
    FOREIGN KEY(ID_FUNCIONARIO) REFERENCES FUNCIONARIOS(ID_FUNCIONARIO)
);

CREATE TABLE TELEFONE_FUNCIONARIOS(
    ID_TELEFONE INT PRIMARY KEY AUTO_INCREMENT,
    TIPO ENUM('RES', 'COM', 'CEL') NOT NULL,
    DDD VARCHAR(5) NOT NULL,
	NUMERO VARCHAR(15) NOT NULL,
    ID_FUNCIONARIO INT UNIQUE,
    FOREIGN KEY(ID_FUNCIONARIO) REFERENCES FUNCIONARIOS(ID_FUNCIONARIO)
);

