
CREATE TABLE FUNCIONARIOS(
    ID_FUNCIONARIO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(16) UNIQUE NOT NULL,
    DATA_NASC DATE,
    SEXO ENUM('M', 'F') NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    MATRICULA VARCHAR(20) UNIQUE NOT NULL,
    SENHA_HASH VARCHAR(255) NOT NULL,
    ID_PERFIL INT NOT NULL,
    FOREIGN KEY (ID_PERFIL) REFERENCES PERFIS(ID)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
)ENGINE=InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE ENDERECO_FUNCIONARIOS(
    ID_ENDERECO INT PRIMARY KEY AUTO_INCREMENT,
    BAIRRO VARCHAR(60) NOT NULL,
	RUA VARCHAR(60) NOT NULL,
	NUMERO INT NOT NULL,
	CIDADE VARCHAR(40) NOT NULL,
	UF CHAR(2) NOT NULL,
    ID_FUNCIONARIO INT UNIQUE,
    FOREIGN KEY(ID_FUNCIONARIO) REFERENCES FUNCIONARIOS(ID_FUNCIONARIO)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE TELEFONE_FUNCIONARIOS(
    ID_TELEFONE INT PRIMARY KEY AUTO_INCREMENT,
    TIPO ENUM('RES', 'COM', 'CEL') NOT NULL,
    DDD VARCHAR(5) NOT NULL,
	NUMERO VARCHAR(15) NOT NULL,
    ID_FUNCIONARIO INT ,
    FOREIGN KEY(ID_FUNCIONARIO) REFERENCES FUNCIONARIOS(ID_FUNCIONARIO)
    ON UPDATE CASCADE
    ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

