CREATE DATABASE MEDIFLOW;

USE MEDIFLOW;

CREATE TABLE PACIENTES(
    ID_PACIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(16) NOT NULL,
    SEXO ENUM('M', 'F') NOT NULL,
    EMAIL VARCHAR(50) UNIQUE,
    DATA_NASC DATE,
    OBSERVACOES TEXT
);

CREATE TABLE ENDERECO_PACIENTES(
    ID_ENDERECO INT PRIMARY KEY AUTO_INCREMENT,
    BAIRRO VARCHAR(60) NOT NULL,
	RUA VARCHAR(60) NOT NULL,
	NUMERO INT NOT NULL,
	CIDADE VARCHAR(40) NOT NULL,
	UF CHAR(2) NOT NULL,
    ID_PACIENTE INT UNIQUE,
    FOREIGN KEY(ID_PACIENTE) REFERENCES PACIENTES(ID_PACIENTE)
);

CREATE TABLE TELEFONE_PACIENTES(
    ID_TELEFONE INT PRIMARY KEY AUTO_INCREMENT,
    TIPO ENUM('RES', 'COM', 'CEL') NOT NULL,
    DDD VARCHAR(5) NOT NULL,
	NUMERO VARCHAR(15) NOT NULL,
    ID_PACIENTE INT UNIQUE,
    FOREIGN KEY(ID_PACIENTE) REFERENCES PACIENTES(ID_PACIENTE)
);

CREATE TABLE FUNCIONARIOS(
    ID_FUNCIONARIO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(16) UNIQUE NOT NULL,
    DATA_NASC DATE,
    SEXO ENUM('M', 'F') NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    MATRICULA VARCHAR(20) UNIQUE NOT NULL,
    SENHA_HASH VARCHAR(255) NOT NULL,
    ID_PERFIL INT NOT NULL,
    FOREIGN KEY (ID_PERFIL) REFERENCES PERFIS(ID)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
)ENGINE=InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE ENDERECO_FUNCIONARIOS(
    ID_ENDERECO INT PRIMARY KEY AUTO_INCREMENT,
    BAIRRO VARCHAR(60) NOT NULL,
	RUA VARCHAR(60) NOT NULL,
	NUMERO INT NOT NULL,
	CIDADE VARCHAR(40) NOT NULL,
	UF CHAR(2) NOT NULL,
    ID_FUNCIONARIO INT UNIQUE,
    FOREIGN KEY(ID_FUNCIONARIO) REFERENCES FUNCIONARIOS(ID_FUNCIONARIO)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE TELEFONE_FUNCIONARIOS(
    ID_TELEFONE INT PRIMARY KEY AUTO_INCREMENT,
    TIPO ENUM('RES', 'COM', 'CEL') NOT NULL,
    DDD VARCHAR(5) NOT NULL,
	NUMERO VARCHAR(15) NOT NULL,
    ID_FUNCIONARIO INT ,
    FOREIGN KEY(ID_FUNCIONARIO) REFERENCES FUNCIONARIOS(ID_FUNCIONARIO)
    ON UPDATE CASCADE
    ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE PROCEDIMENTOS(
ID INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(100) NOT NULL,
CATEGORIA ENUM('CONSULTA', 'EXAME LABORATORIAL', 'EXAME DE IMAGEM', 'VACINA') NOT NULL,
PRECO DECIMAL(10, 2) NOT NULL,
DESCRICAO TEXT,
ATIVO BOOLEAN DEFAULT TRUE,
TEMPO_ESTIMADO TIME
);

-- Alguns inserts para povoar a tabela de procedimentos:

INSERT INTO PROCEDIMENTOS (NOME, CATEGORIA, PRECO, DESCRICAO, TEMPO_ESTIMADO) VALUES
('Consulta Clínica Geral', 'CONSULTA', 120.00, 'Consulta de rotina com médico clínico geral.', '00:30:00'),
('Hemograma Completo', 'EXAME LABORATORIAL', 85.50, 'Exame de sangue para avaliação geral da saúde.', '00:15:00'),
('Raio-X Tórax', 'EXAME DE IMAGEM', 150.75, 'Radiografia da região torácica para diagnóstico de diversas condições.', '00:20:00'),
('Vacina Antigripal', 'VACINA', 60.00, 'Vacina contra o vírus Influenza (gripe).', '00:10:00'),
('Consulta com Cardiologista', 'CONSULTA', 250.00, 'Consulta especializada com médico cardiologista.', '00:45:00'),
('Glicemia em Jejum', 'EXAME LABORATORIAL', 35.20, 'Exame para medir o nível de glicose no sangue após jejum.', '00:05:00'),
('Ultrassonografia Abdominal', 'EXAME DE IMAGEM', 220.90, 'Exame de imagem para visualização dos órgãos internos do abdômen.', '00:35:00'),
('Vacina Tríplice Viral (Sarampo, Caxumba, Rubéola)', 'VACINA', 95.00, 'Vacina combinada contra sarampo, caxumba e rubéola.', '00:15:00'),
('Consulta com Dermatologista', 'CONSULTA', 180.50, 'Consulta especializada com médico dermatologista.', '00:40:00'),
('Cultura de Urina', 'EXAME LABORATORIAL', 70.00, 'Exame laboratorial para identificar bactérias em amostra de urina.', '00:25:00');

-- Tabela que define quais os possíveis perfis para cadastro de usuários:
CREATE TABLE PERFIS(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(50) UNIQUE NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Insert com os possíveis perfis:
INSERT INTO PERFIS(NOME) 
VALUES ('ADMIN'),
('RECEPCIONISTA'), ('MEDICO');

-- Tabela que será utilizada para agendamento de consultas:
CREATE TABLE AGENDAMENTOS(
    ID_AGENDAMENTO INT PRIMARY KEY AUTO_INCREMENT,
    TIPO ENUM('CONSULTA', 'EXAME LABORATORIAL', 'EXAME DE IMAGEM', 'VACINA') NOT NULL,
    ID_PACIENTE INT NOT NULL,
    ID_PROFISSIONAL INT NOT NULL,
    DATA_HORA DATETIME NOT NULL,
    OBSERVACOES TEXT,
    FOREIGN KEY(ID_PACIENTE) REFERENCES PACIENTES(ID_PACIENTE),
    FOREIGN KEY(ID_PROFISSIONAL) REFERENCES FUNCIONARIOS(ID_FUNCIONARIO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;