CREATE DATABASE MEDIFLOW;

CREATE TABLE PROCEDIMENTOS(
ID INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(100) NOT NULL,
CATEGORIA ENUM('CONSULTA', 'EXAME LABORATORIAL', 'EXAME DE IMAGEM', 'VACINA') NOT NULL,
PRECO DECIMAL(10, 2) NOT NULL,
DESCRICAO TEXT,
ATIVO BOOLEAN DEFAULT TRUE,
TEMPO_ESTIMADO TIME
);

	