CREATE TABLE PACIENTES(
    ID_PACIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(16) NOT NULL,
    SEXO ENUM('M', 'F') NOT NULL,
    EMAIL VARCHAR(50) UNIQUE,
    DATA_NASC DATE,
    OBSERVACOES TEXT
);

CREATE TABLE ENDERECO_PACIENTES(
    ID_ENDERECO INT PRIMARY KEY AUTO_INCREMENT,
    BAIRRO VARCHAR(60) NOT NULL,
	RUA VARCHAR(60) NOT NULL,
	NUMERO INT NOT NULL,
	CIDADE VARCHAR(40) NOT NULL,
	UF CHAR(2) NOT NULL,
    ID_PACIENTE INT UNIQUE,
    FOREIGN KEY(ID_PACIENTE) REFERENCES PACIENTES(ID_PACIENTE)
);

CREATE TABLE TELEFONE_PACIENTES(
    ID_TELEFONE INT PRIMARY KEY AUTO_INCREMENT,
    TIPO ENUM('RES', 'COM', 'CEL') NOT NULL,
    DDD VARCHAR(5) NOT NULL,
	NUMERO VARCHAR(15) NOT NULL,
    ID_PACIENTE INT UNIQUE,
    FOREIGN KEY(ID_PACIENTE) REFERENCES PACIENTES(ID_PACIENTE)
);

