CREATE TABLE PERFIS(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(50) UNIQUE NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO PERFIS(NOME) 
VALUES ('ADMIN'),
('RECEPCIONISTA'), ('MEDICO');

