CREATE TABLE PACIENTES(
    ID_PACIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(16) NOT NULL,
    SEXO ENUM('M', 'F') NOT NULL,
    EMAIL VARCHAR(50) UNIQUE,
    DATA_NASC DATE,
    OBSERVACOES TEXT
);